// <auto-generated />
namespace Cinema_WPF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ChangePassword_1Migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangePassword_1Migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201708251403281_ChangePassword_1Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
